import json
import os

from bundle import QUESTS_DIR
from logger import capture

# Optional harder quest islands: villages/quests_hard/<same name>, generated by
# tools/make_harder_quests.py from the originals, which stay untouched. Off by
# default, like the other switches in this project (SE_VERBOSE, SE_CAPTURE,
# SE_BACKUP_SECONDS). Changing it needs a restart: the loaded quests are cached.
HARD_QUESTS = os.environ.get("SE_HARD_QUESTS", "0") not in ("", "0", "false", "False")
HARD_QUESTS_DIR = os.path.join(os.path.dirname(QUESTS_DIR), "quests_hard")

_quest_cache = {}


def _quest_path(questid):
    """Serve the harder variant when it is enabled and present, else the original."""
    if HARD_QUESTS:
        harder = os.path.join(HARD_QUESTS_DIR, str(questid) + ".json")
        if os.path.exists(harder):
            return harder
    return os.path.join(QUESTS_DIR, str(questid) + ".json")


def get_quest_map(questid):
    if questid in _quest_cache:
        return (_quest_cache[questid], 200)
    file = _quest_path(questid)
    if not os.path.exists(file):
        # The client asked for an island the server does not have. With SE_CAPTURE on
        # this records exactly which ids the client knows about, which is the only
        # way to learn whether brand new islands are reachable at all.
        capture({"route": "quest", "questid": str(questid), "found": False})
        return("", 404)
    with open(file, 'r', encoding='utf-8') as f:
        d = json.load(f)
    _quest_cache[questid] = d
    # Only on a cache miss, so one line per island per run rather than per request.
    capture({"route": "quest", "questid": str(questid), "found": True,
             "source": "hard" if HARD_QUESTS and "quests_hard" in file else "original"})
    return(d, 200)
